# git clone https//github.com/codebyhenry/dockerfiles/gitlab/docker-compose.yml
# https://docs.gitlab.com/ee/install/docker.html

# For Linux users, set the path to /srv/gitlab:
# sudo export GITLAB_HOME=/srv/gitlab

# For macOS users, use the user’s $HOME/gitlab directory:
# export GITLAB_HOME=$HOME/gitlab

version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    ports:
      - "9992:22"
      - "9980:80"
      - "9983:443"
    volumes:
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/config:/etc/gitlab
    shm_size: '256m'

# for docker swarm uncomment below 

#    environment:
#      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
#    configs:
#      - source: gitlab
#        target: /omnibus_config.rb
#    secrets:
#      - gitlab_root_password
#  gitlab-runner:
#    image: gitlab/gitlab-runner:alpine
#    deploy:
#      mode: replicated
#      replicas: 4
#configs:
#  gitlab:
#    file: ./gitlab.rb
#secrets:
#  gitlab_root_password:
#    file: ./root_password.txt
